spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: msvc-shoppingcart
          uri: lb://msvc-shoppingcart
          predicates:
            - Path=/api/shoppingcart/**
          filters:
            - StripPrefix=2
        - id: images-service-service
          uri: lb://images-service-service
          predicates:
            - Path=/api/images/**
          filters:
            - StripPrefix=2
        - id: user-msvc-service
          uri: lb://user-msvc-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=2